import { Ionicons } from '@expo/vector-icons';
import Constants from 'expo-constants';
import { useRouter, useLocalSearchParams } from 'expo-router';
import React, { useState, useEffect } from 'react';
import {
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Animated,
} from 'react-native';

const HEADER_HEIGHT = Constants.statusBarHeight + 130;

// 챌린지 아이템 타입 정의
interface Challenge {
  id: string;
  title: string;
  description: string;
  icon: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  completed: boolean;
}

export default function ChallengeScreen() {
  const router = useRouter();
  const params = useLocalSearchParams(); // 리포트에서 넘어온 파라미터 수신

  const [challenges, setChallenges] = useState<Challenge[]>([]);

  // 리포트 생성 시 자동으로 챌린지 생성 로직 시뮬레이션
  useEffect(() => {
    // 리포트에서 "생성됨" 신호가 오거나 페이지가 로드될 때 더미 데이터 생성
    const autoGeneratedChallenges: Challenge[] = [
      {
        id: '1',
        title: '감정 단어 3개 기록하기',
        description:
          '오늘 느낀 감정을 단순히 "좋다", "나쁘다"가 아닌 구체적인 단어로 적어보세요.',
        icon: 'book-outline',
        difficulty: 'Easy',
        completed: false,
      },
      {
        id: '2',
        title: '의도적인 거절 연습',
        description:
          '무리한 부탁에 대해 정중하지만 확실하게 거절의 의사를 표현해보세요.',
        icon: 'shield-checkmark-outline',
        difficulty: 'Medium',
        completed: false,
      },
      {
        id: '3',
        title: '30분간 디지털 디톡스',
        description:
          '스마트폰을 멀리하고 오직 나 자신의 생각에만 집중하는 시간을 가집니다.',
        icon: 'leaf-outline',
        difficulty: 'Hard',
        completed: false,
      },
    ];
    setChallenges(autoGeneratedChallenges);
  }, [params.reportId]); // 새로운 리포트 ID가 올 때마다 챌린지 갱신

  const toggleComplete = (id: string) => {
    setChallenges((prev) =>
      prev.map((c) => (c.id === id ? { ...c, completed: !c.completed } : c)),
    );
  };

  return (
    <View style={styles.fullContainer}>
      <StatusBar barStyle="light-content" />
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => router.replace('/(tabs)')}
          style={styles.backBtn}
        >
          <Ionicons name="chevron-back" size={28} color="#fff" />
        </TouchableOpacity>
        <View style={styles.profileArea}>
          <View style={styles.avatar}>
            <Ionicons name="person" size={32} color="#2D3436" />
          </View>
          <Text style={styles.profileName}>현식님</Text>
          <Text style={styles.mbtiTag}>성장 챌린지</Text>
        </View>
      </View>

      <ScrollView
        contentContainerStyle={{ padding: 20 }}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.titleSection}>
          <Text style={styles.title}>오늘의 미션</Text>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>AI 분석 완료</Text>
          </View>
        </View>

        <Text style={styles.subtitle}>
          최근 리포트를 바탕으로 생성된 맞춤 챌린지입니다.
        </Text>

        {challenges.map((item) => (
          <TouchableOpacity
            key={item.id}
            style={[styles.card, item.completed && styles.completedCard]}
            onPress={() => toggleComplete(item.id)}
            activeOpacity={0.8}
          >
            <View style={styles.cardIcon}>
              <Ionicons
                name={item.completed ? 'checkmark-circle' : (item.icon as any)}
                size={30}
                color={item.completed ? '#00B894' : '#6C5CE7'}
              />
            </View>
            <View style={styles.cardContent}>
              <View style={styles.cardHeaderRow}>
                <Text
                  style={[
                    styles.cardTitle,
                    item.completed && styles.completedText,
                  ]}
                >
                  {item.title}
                </Text>
                <View
                  style={[
                    styles.diffBadge,
                    styles[
                      item.difficulty.toLowerCase() as
                        | 'easy'
                        | 'medium'
                        | 'hard'
                    ],
                  ]}
                >
                  <Text style={styles.diffText}>{item.difficulty}</Text>
                </View>
              </View>
              <Text
                style={[
                  styles.cardDesc,
                  item.completed && styles.completedText,
                ]}
              >
                {item.description}
              </Text>
            </View>
          </TouchableOpacity>
        ))}

        {challenges.length > 0 && (
          <View style={styles.infoBox}>
            <Ionicons
              name="information-circle-outline"
              size={20}
              color="#7F8C8D"
            />
            <Text style={styles.infoText}>
              챌린지를 완료하면 내면 성장 포인트가 적립됩니다.
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  fullContainer: { flex: 1, backgroundColor: '#F5F7F9' },
  header: {
    height: HEADER_HEIGHT,
    paddingTop: Constants.statusBarHeight + 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2D3436',
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
  },
  backBtn: {
    position: 'absolute',
    left: 20,
    top: Constants.statusBarHeight + 35,
  },
  profileArea: { alignItems: 'center' },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileName: { fontWeight: '700', fontSize: 18, color: '#fff' },
  mbtiTag: { fontSize: 12, color: '#A29BFE' },

  titleSection: { flexDirection: 'row', alignItems: 'center', marginTop: 25 },
  title: { fontSize: 24, fontWeight: '800', color: '#2D3436' },
  badge: {
    backgroundColor: '#E0DEFF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 10,
  },
  badgeText: { color: '#6C5CE7', fontSize: 11, fontWeight: '700' },

  subtitle: { color: '#7F8C8D', fontSize: 14, marginTop: 5, marginBottom: 25 },

  card: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 22,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  completedCard: {
    backgroundColor: '#F0FFF4',
    borderColor: '#00B894',
  },
  cardIcon: {
    justifyContent: 'center',
    marginRight: 15,
  },
  cardContent: { flex: 1 },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  cardTitle: { fontSize: 16, fontWeight: '700', color: '#2D3436' },
  cardDesc: { fontSize: 13, color: '#636E72', lineHeight: 18 },
  completedText: { color: '#B2BEC3', textDecorationLine: 'line-through' },

  diffBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  easy: { backgroundColor: '#E1F5FE' },
  medium: { backgroundColor: '#FFF3E0' },
  hard: { backgroundColor: '#FFEBEE' },
  diffText: { fontSize: 10, fontWeight: '700', color: '#555' },

  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    opacity: 0.7,
  },
  infoText: { marginLeft: 8, fontSize: 12, color: '#7F8C8D' },
});
