import { Ionicons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';
import React, { useState, useEffect, useRef } from 'react';
import {
  ScrollView,
  StatusBar,
  Text,
  TouchableOpacity,
  View,
  Animated,
  Dimensions,
} from 'react-native';

import styles from '../../css/challengePage';
import globalStyles from '../../css/globalStyles';

const { width, height } = Dimensions.get('window');

interface Challenge {
  id: string;
  title: string;
  description: string;
  icon: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  completed: boolean;
}

export default function ChallengeScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  const [challenges, setChallenges] = useState<Challenge[]>([]);

  // --- 배경 애니메이션 (일관성 유지) ---
  const moveAnim1 = useRef(
    new Animated.ValueXY({ x: width * 0.2, y: height * 0.2 }),
  ).current;
  const moveAnim2 = useRef(
    new Animated.ValueXY({ x: width * 0.6, y: height * 0.7 }),
  ).current;

  useEffect(() => {
    const createBouncingAnim = (anim: Animated.ValueXY) => {
      Animated.timing(anim, {
        toValue: {
          x: Math.random() * (width - 150),
          y: Math.random() * (height - 150),
        },
        duration: Math.random() * 3000 + 5000,
        useNativeDriver: false,
      }).start(() => createBouncingAnim(anim));
    };
    createBouncingAnim(moveAnim1);
    createBouncingAnim(moveAnim2);

    const autoGeneratedChallenges: Challenge[] = [
      {
        id: '1',
        title: '감정 단어 3개 기록하기',
        description: '오늘 느낀 감정을 구체적인 단어로 적어보세요.',
        icon: 'book-outline',
        difficulty: 'Easy',
        completed: false,
      },
      {
        id: '2',
        title: '의도적인 거절 연습',
        description: '정중하지만 확실하게 거절의 의사를 표현해보세요.',
        icon: 'shield-checkmark-outline',
        difficulty: 'Medium',
        completed: false,
      },
      {
        id: '3',
        title: '30분간 디지털 디톡스',
        description: '스마트폰을 멀리하고 나 자신의 생각에 집중하세요.',
        icon: 'leaf-outline',
        difficulty: 'Hard',
        completed: false,
      },
    ];
    setChallenges(autoGeneratedChallenges);
  }, [params.reportId]);

  const toggleComplete = (id: string) => {
    setChallenges((prev) =>
      prev.map((c) => (c.id === id ? { ...c, completed: !c.completed } : c)),
    );
  };

  return (
    <View style={globalStyles.recordBackground}>
      <StatusBar
        barStyle="light-content"
        translucent
        backgroundColor="transparent"
      />

      {/* 배경 애니메이션 원 */}
      <Animated.View
        style={[globalStyles.topBlurCircle, moveAnim1.getLayout()]}
      />
      <Animated.View
        style={[globalStyles.bottomBlurCircle, moveAnim2.getLayout()]}
      />

      {/* 헤더 영역 (슬림 디자인) */}
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <TouchableOpacity
            onPress={() => router.replace('/(tabs)')}
            style={styles.backBtn}
          >
            <Ionicons name="chevron-back" size={24} color="#fff" />
          </TouchableOpacity>
          <View style={styles.profileInfo}>
            <Text style={styles.profileName}>현식님</Text>
            <Text style={styles.mbtiTag}>성장 챌린지</Text>
          </View>
        </View>
        <Ionicons
          name="flash"
          size={24}
          color="#FF4D4D"
          style={{ marginRight: 5 }}
        />
      </View>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.titleSection}>
          <Text style={styles.title}>오늘의 미션</Text>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>AI 분석 완료</Text>
          </View>
        </View>

        <Text style={styles.subtitle}>
          최근 리포트를 바탕으로 생성된 맞춤 챌린지입니다.
        </Text>

        {challenges.map((item) => (
          <TouchableOpacity
            key={item.id}
            style={[styles.card, item.completed && styles.completedCard]}
            onPress={() => toggleComplete(item.id)}
            activeOpacity={0.8}
          >
            <View style={styles.cardIcon}>
              <Ionicons
                name={item.completed ? 'checkmark-circle' : (item.icon as any)}
                size={28}
                color={item.completed ? '#00B894' : '#FF4D4D'}
              />
            </View>
            <View style={styles.cardContent}>
              <View style={styles.cardHeaderRow}>
                <Text
                  style={[
                    styles.cardTitle,
                    item.completed && styles.completedText,
                  ]}
                >
                  {item.title}
                </Text>
                <View
                  style={[
                    styles.diffBadge,
                    styles[
                      item.difficulty.toLowerCase() as
                        | 'easy'
                        | 'medium'
                        | 'hard'
                    ],
                  ]}
                >
                  <Text style={styles.diffText}>{item.difficulty}</Text>
                </View>
              </View>
              <Text
                style={[
                  styles.cardDesc,
                  item.completed && styles.completedText,
                ]}
              >
                {item.description}
              </Text>
            </View>
          </TouchableOpacity>
        ))}

        {challenges.length > 0 && (
          <View style={styles.infoBox}>
            <Ionicons
              name="information-circle-outline"
              size={18}
              color="#555"
            />
            <Text style={styles.infoText}>
              챌린지를 완료하면 내면 성장 포인트가 적립됩니다.
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}
